import React from "react";
import Footer from "../components/Footer/Footer";
import Nav from "../components/Nav/Nav/Nav";
import Head from "next/head";
import { Container } from "@mui/material";
import theme from "./../themes/theme";
import { ThemeProvider } from "@mui/material/styles";

interface Props {
  children: React.ReactNode;
}

export default function MainLayout(props: Props) {
  const { children } = props;
  return (
    <React.Fragment>
      <ThemeProvider theme={theme}>
        <Head>
          <title>r-mui</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Nav />
          <Container>{children}</Container>
        </main>
        <Footer />
      </ThemeProvider>
    </React.Fragment>
  );
}
